### ISSUE TITLE
请教下，怎么改成CBC加密、pkcs5填充、128位的方式

### ISSUE THREAD

**Issue by ydz00ydz** [wtuadn/JNITool#1]
你好，刚开始学JNI开发，想问下能改成CBC加密、pkcs5填充、128位的方式吗？

**Comment by wtuadn** [comment]
> 你好，刚开始学JNI开发，想问下能改成CBC加密、pkcs5填充、128位的方式吗？

- 使用长度为16的密钥就会自动使用128位
- pkcs5和pkcs7实际是一样的
- CBC加密方式在library/src/main/cpp/jni_tool.cpp文件里搜索CBC可以找到注释掉的代码
