### ISSUE TITLE
长字符串解密总是在48位开始出现乱码

### ISSUE THREAD

**Issue by ydz00ydz** [wtuadn/JNITool#2]
你好，上个问题按您的方法解决了，改成CBC加密、PKCS5填充了。
短字符串加解密都没问题，但是字符串超过48位就会出现乱码。

key和iv都是"1234567890123456"，
明文"01234567890123456789012345678901234567890123456789"
加密后"9d2e5ab8f8e77eb24b495dd4c7aca762106eb0043b06eb028967719572a565d5c4aa3d5ccd26ea743fcaaeceb39a9bc301b22ee471aff7c39936120f6b3a38bc"
该密文正确，并且通过在线解密可以正确解密。
但是代码解密的话会是"012345678901234567890123456789012345678901234567r�3jÿ"。
可能是什么地方出错了？

**Comment by ydz00ydz** [comment]
可能是base64加密问题，C与Java加密结果在特殊字符上有区别。

**Comment by wtuadn** [comment]
> 可能是base64加密问题，C与Java加密结果在特殊字符上有区别。

jni_tool.cpp里key和iv都是"1234567890123456"，CBC加密，我就改了MainActivity的originalStr为"01234567890123456789012345678901234567890123456789"，是能正常加解密的，你说的代码解密乱码是怎么样解密的

**Comment by ydz00ydz** [comment]
> > 可能是base64加密问题，C与Java加密结果在特殊字符上有区别。
> 
> jni_tool.cpp里key和iv都是"1234567890123456"，CBC加密，我就改了MainActivity的originalStr为"01234567890123456789012345678901234567890123456789"，是能正常加解密的，你说的代码解密乱码是怎么样解密的

麻烦了，已经找到了，和你的代码没关系，是我java里的Base64加密方式选错了，应该用Base64.URL_SAFE。
