### ISSUE TITLE
Can  modify to support gradle plugin ?

### ISSUE THREAD

**Issue by CMingTseng** [wtuadn/JNITool#4]
Dear Sir 

i want use  AES at build.gradle 

to  add a task ency a String into file 

can teach me ?

THX

**Comment by wtuadn** [comment]
> Dear Sir
> 
> i want use AES at build.gradle
> 
> to add a task ency a String into file
> 
> can teach me ?
> 
> THX

Sorry, i do`t know much about this, maybe you can google "gradle aes".
